/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "baseUrl": "/",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "es",
      "fr",
      "pt-br",
      "tr",
      "ko"
    ],
    "localeConfigs": {
      "en": {
        "label": "English",
        "direction": "ltr"
      },
      "es": {
        "label": "Español",
        "direction": "ltr"
      },
      "fr": {
        "label": "Français",
        "direction": "ltr"
      },
      "pt-br": {
        "label": "Português (Brasil)",
        "htmlLang": "pt-BR",
        "direction": "ltr"
      },
      "tr": {
        "label": "Türkçe",
        "direction": "ltr"
      },
      "ko": {
        "label": "한국어",
        "direction": "ltr"
      }
    },
    "path": "i18n"
  },
  "favicon": "img/favicon.ico",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "throw",
  "organizationName": "analogjs",
  "plugins": [],
  "presets": [
    [
      "classic",
      {
        "blog": false,
        "docs": {
          "editUrl": "https://github.com/analogjs/analog/edit/main/apps/docs-app",
          "sidebarPath": "/Volumes/SnyderDev/@benpsnyder/nx-bun-testing/apps/docs-app/sidebars.js"
        },
        "theme": {
          "customCss": "/Volumes/SnyderDev/@benpsnyder/nx-bun-testing/apps/docs-app/src/css/custom.css"
        }
      }
    ]
  ],
  "projectName": "analog",
  "tagline": "The fullstack Angular meta-framework",
  "themeConfig": {
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "image": "img/logos/analog-logo.svg",
    "footer": {
      "logo": {
        "alt": "Analog logo",
        "href": "/",
        "src": "img/logos/analog-logo.svg"
      },
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Introduction",
              "to": "docs"
            },
            {
              "label": "Getting Started",
              "to": "docs/getting-started"
            }
          ]
        },
        {
          "title": "Open source",
          "items": [
            {
              "label": "Contributors",
              "to": "docs/contributors"
            },
            {
              "label": "Contributing",
              "to": "docs/contributing"
            },
            {
              "label": "Sponsor",
              "to": "docs/sponsoring"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/analogjs/analog"
            },
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/analogjs"
            }
          ]
        }
      ],
      "copyright": "\n          Copyright © 2022-2024 Analog. Licensed under MIT.\n          <p>\n            <a href=\"https://www.netlify.com\"> <img src=\"https://www.netlify.com/v3/img/components/netlify-color-accent.svg\" alt=\"Deploys by Netlify\" /> </a>\n          </p>\n        ",
      "style": "light"
    },
    "navbar": {
      "title": "Analog",
      "hideOnScroll": true,
      "logo": {
        "alt": "Analog logo",
        "src": "img/logos/analog-logo.svg"
      },
      "items": [
        {
          "activeBasePath": "docs",
          "label": "Docs",
          "position": "left",
          "to": "docs"
        },
        {
          "href": "https://github.com/analogjs/analog",
          "label": "GitHub",
          "position": "right"
        },
        {
          "href": "https://chat.analogjs.org",
          "label": "Discord",
          "position": "right"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ]
    },
    "prism": {
      "defaultLanguage": "typescript",
      "theme": {
        "plain": {
          "color": "#403f53",
          "backgroundColor": "#FBFBFB"
        },
        "styles": [
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(162, 191, 252)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgba(239, 83, 80, 0.56)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "inserted",
              "attr-name"
            ],
            "style": {
              "color": "rgb(72, 118, 214)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(152, 159, 177)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "builtin",
              "char",
              "constant",
              "url"
            ],
            "style": {
              "color": "rgb(72, 118, 214)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(201, 103, 101)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(170, 9, 130)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "rgb(153, 76, 195)"
            }
          },
          {
            "types": [
              "function",
              "selector",
              "doctype"
            ],
            "style": {
              "color": "rgb(153, 76, 195)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(17, 17, 17)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(153, 76, 195)"
            }
          },
          {
            "types": [
              "operator",
              "property",
              "keyword",
              "namespace"
            ],
            "style": {
              "color": "rgb(12, 150, 155)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(188, 84, 84)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#d6deeb",
          "backgroundColor": "#0a1429"
        },
        "styles": [
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(162, 191, 252)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgba(239, 83, 80, 0.56)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "inserted",
              "attr-name"
            ],
            "style": {
              "color": "rgb(173, 219, 103)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(99, 119, 119)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "url"
            ],
            "style": {
              "color": "rgb(173, 219, 103)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(214, 222, 235)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "selector",
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(255, 203, 139)"
            }
          },
          {
            "types": [
              "tag",
              "operator",
              "keyword"
            ],
            "style": {
              "color": "rgb(127, 219, 202)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "property"
            ],
            "style": {
              "color": "rgb(128, 203, 196)"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "toml",
        "json",
        "bash"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "algolia": {
      "appId": "8W3CAMYOQF",
      "apiKey": "650d723674c8cd38658add35fb9433e3",
      "indexName": "analogjs",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "title": "Analog",
  "trailingSlash": false,
  "url": "https://analogjs.org",
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
